config/routes.rb
PrismBreak::Application.routes.draw do
  resources :platform_types do
    resources :platforms
  end

  resources :platforms do
    resources :categories
  end

  resources :categories do
    resources :softwares, path: 'software' do
      get 'history', on: :member
    end
  end

  resources :protocols do
    get 'history', on: :member
  end

  get 'media', to: 'pages#media'

  filter :locale

  root 'pages#index'

  

end

app/controllers/platform_types_controller.rb
class PlatformTypesController < ApplicationController
  before_action :set_platform_type, only: [:show, :edit, :update, :destroy]

  # GET /platform_types
  # GET /platform_types.json
  def index
    @platform_types = PlatformType.all
    @parent_path = root_path
    @page_title = t 'v.platform_types.plural'
  end

  # GET /platform_types/1
  # GET /platform_types/1.json
  def show
    @parent_path = platform_types_path
    @page_title = @platform_type.title
  end

  # GET /platform_types/new
  def new
    @platform_type = PlatformType.new
    @parent_path = root_path
    @page_title = t 'v.platform_types.new'
  end

  # GET /platform_types/1/edit
  def edit
    @parent_path = @platform_type
    @page_title =  t 'v.platform_types.edit'
  end

  # POST /platform_types
  # POST /platform_types.json
  def create
    @platform_type = PlatformType.new(platform_type_params)

    respond_to do |format|
      if @platform_type.save
        format.html { redirect_to @platform_type, notice: 'Platform type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @platform_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @platform_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platform_types/1
  # PATCH/PUT /platform_types/1.json
  def update
    respond_to do |format|
      if @platform_type.update(platform_type_params)
        format.html { redirect_to @platform_type, notice: 'Platform type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @platform_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platform_types/1
  # DELETE /platform_types/1.json
  def destroy
    @platform_type.destroy
    respond_to do |format|
      format.html { redirect_to platform_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform_type
      @platform_type = PlatformType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_type_params
      params.require(:platform_type).permit(:title)
    end
end

app/helpers/platform_types_helper.rb
module PlatformTypesHelper
end

app/views/platform_types/_form.html.slim
= form_for @platform_type do |f|
  - if @platform_type.errors.any?
    #error_explanation
      h2 = "#{pluralize(@platform_type.errors.count, "error")} prohibited this platform_type from being saved:"
      ul
        - @platform_type.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title

  .pipe Actions
  = content_tag :button, type: 'submit', class: 'bar' do
    .label= t 'verb.Save'
    .icon= fa_icon 'save'

app/views/platform_types/edit.html.slim
== render 'form'

app/views/platform_types/index.html.slim
- @platform_types.order(:title).each do |platform_type|
  = link_to platform_type.title, platform_type, class: 'pipe'
  - platform_type.platforms.order(:title).each do |platform|
    = link_to platform, class: 'bar' do
      .label
        = t 'verbs.browse'
        '
        strong= platform.title
        '
        span.light= "(#{platform.software_count})"
      .icon= fa_icon 'angle-right'

.pipe= t 'Administration'
= link_to new_category_path, class: 'bar' do
  .label
    = t 'v.platforms.new'
  .icon= fa_icon 'plus'

= link_to new_platform_type_path, class: 'bar' do
  .label
    = t 'v.platform_types.new'
  .icon= fa_icon 'plus'

app/views/platform_types/new.html.slim
== render 'form'

app/views/platform_types/show.html.slim
p#notice = notice

- @platform_type.platforms.order(:title).each do |platform|
  = link_to platform, class: 'bar' do
    .label
      = t 'verbs.browse'
      '
      strong= platform.title
      '
      span.light= "(#{platform.software_count})"
    .icon= fa_icon 'angle-right'

.pipe= t 'Administration'
= link_to new_platform_type_platform_path(@platform_type), class: 'bar' do
  .label
    = t 'v.platforms.new'
    '
    = t 'in'
    '
    = @platform_type.title
  .icon= fa_icon 'plus'


= link_to edit_platform_type_path(@platform_type), class: 'bar' do
  .label
    = t 'v.platform_types.edit'
  .icon= fa_icon 'edit'

= link_to @platform_type, :confirm => 'Are you sure?', :method => :delete, class: 'bar' do
  .label= t 'v.platform_types.destroy'
  .icon= fa_icon 'trash-o'