config/routes.rb
PrismBreak::Application.routes.draw do
  resources :platform_types do
    resources :platforms
  end

  resources :platforms do
    resources :categories
  end

  resources :categories do
    resources :softwares, path: 'software' do
      get 'history', on: :member
    end
  end

  resources :protocols do
    get 'history', on: :member
  end

  get 'media', to: 'pages#media'

  filter :locale

  root 'pages#index'

  

end

app/models/platform_type.rb
class PlatformType < ActiveRecord::Base
  # associations
  has_many :platforms

  # translations
  translates :title, :versioning => true

  # validations
  validates :title, presence: true, uniqueness: true
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  # GET /platforms
  # GET /platforms.json
  def index
    @parent_path = root_path
    @page_title = t 'v.platforms.plural'
    @platforms = Platform.all
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
    @parent_path = root_path
    @page_title = @platform.title
  end

  # GET /platforms/new
  def new
    @parent_path = platforms_path
    @page_title = t 'v.platforms.new'
    @platform = Platform.new
    @platform_types = PlatformType.all
  end

  # GET /platforms/1/edit
  def edit
    @parent_path = @platform
    @page_title = t 'v.platforms.edit'
    @platform_types = PlatformType.all
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(platform_params)

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render action: 'show', status: :created, location: @platform }
      else
        format.html { render action: 'new' }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1
  # PATCH/PUT /platforms/1.json
  def update
    @parent_path = @platform
    @page_title = t 'v.platforms.edit'
    @platform_types = PlatformType.all
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform.destroy
    respond_to do |format|
      format.html { redirect_to platforms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_params
      params.require(:platform).permit(:title, :description, :wikipedia_url, :platform_type_id)
    end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.slim
= form_for @platform do |f|
  - if @platform.errors.any?
    #error_explanation
      h2 = "#{pluralize(@platform.errors.count, "error")} prohibited this platform from being saved:"
      ul
        - @platform.errors.full_messages.each do |message|
          li = message

  .field
    = f.label t 'Title'
    = f.text_field :title
  .field
    = f.label t 'Description'
    = f.text_area :description
  .field
    = f.label t 'Wikipedia URL'
    = f.text_field :wikipedia_url
  .field
    = f.label t('Platform Type')
    ul.checkboxes
      - @platform_types.order(:title).each do |platform_type| 
        li.checkbox
          - if platform_type.id == params[:platform_type_id].to_i
            = f.radio_button :platform_type_id, platform_type.id, id: "category_check_#{platform_type.id}", checked: true
          - else
            = f.radio_button :platform_type_id, platform_type.id, id: "category_check_#{platform_type.id}"
          = f.label "check_#{platform_type.id}", platform_type.title

  .pipe Actions
  = content_tag :button, type: 'submit', class: 'bar' do
    .label= t 'verb.Save'
    .icon= fa_icon 'save'

app/views/platforms/index.html.slim
- @platforms.order(:title).each do |platform|
  = link_to platform, class: 'bar' do
    .label= platform.title
    .icon= fa_icon 'external-link-o'

= link_to new_platform_path, class: 'bar' do
  .label= t 'v.platforms.new'
  .icon= fa_icon 'edit'

app/views/platforms/show.html.slim
p#notice = notice

- @platform.categories.order(:title).each do |category|
  - if category.softwares.count == 0
    = link_to platform_category_path(@platform, category), class: 'bar' do
      .label
        = category.title
        '
        span.light= "(#{category.softwares.count})"
      .icon= fa_icon 'angle-right'

  - else
    = link_to platform_category_path(@platform, category), class: 'bar' do
      .label
        = image_tag category.softwares.order(:title).first.logo.url(:'medium@2x'), class: 'logo', width: 29, height: 29
        = category.title
        '
        span.light= "(#{category.softwares.count})"
      .icon= fa_icon 'angle-right'


.pipe= t 'Administration'

= link_to new_platform_category_path(@platform), class: 'bar' do
  .label
    = t 'v.categories.new'
    '
    = t 'in'
    '
    = @platform.title
  .icon= fa_icon 'plus'

= link_to edit_platform_path(@platform), class: 'bar' do
  .label= t 'v.platforms.edit'
  .icon= fa_icon 'edit'

= link_to @platform, :confirm => 'Are you sure?', :method => :delete, class: 'bar' do
  .label= t 'v.platforms.destroy'
  .icon= fa_icon 'trash-o'