config/routes.rb
PrismBreak::Application.routes.draw do
  resources :platform_types do
    resources :platforms
  end

  resources :platforms do
    resources :categories
  end

  resources :categories do
    resources :softwares, path: 'software' do
      get 'history', on: :member
    end
  end

  resources :protocols do
    get 'history', on: :member
  end

  get 'media', to: 'pages#media'

  filter :locale

  root 'pages#index'

  

end

app/models/software.rb
class Software < ActiveRecord::Base
  # associations
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :protocol_softwares
  has_many :protocols, through: :protocol_softwares

  # translations and edit history
  translates :title, :description, :url, :source_url, :privacy_url, :tos_url, :license_url, :wikipedia_url, :notes, :versioning => true
  has_paper_trail
  
  # paperclip
  has_attached_file :logo,
    :styles => {
      #:'huge@2x'   => ["1024x1024>", :png],
      #:'huge'      => ["512x512>",   :png],
      #:'large@2x'  => ["480x480>",   :png],
      #:'large'     => ["240x240>",   :png],
      :'medium@2x' => ["120x120>",   :png],
      :'medium'    => ["60x60>",     :png],
      #:'small@2x'  => ["80x80>",     :png],
      #:'small'     => ["40x40>",     :png],
      #:'tiny@2x'   => ["48x48>",     :png],
      #:'tiny'      => ["24x24>",     :png]
    },
    :path => ":rails_root/public/system/:class/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:class/:attachment/:id/:basename_:style.:extension",
    :default_url => "/images/:style/missing.png",
    :convert_options => {
      :'huge@2x'   => "-background none -gravity center -extent 1024x1024",
      :'huge'      => "-background none -gravity center -extent 512x512",
      :'large@2x'  => "-background none -gravity center -extent 480x480",
      :'largex'    => "-background none -gravity center -extent 240x240",
      :'medium@2x' => "-background none -gravity center -extent 120x120",
      :'medium'    => "-background none -gravity center -extent 60x60",
      :'small@2x'  => "-background none -gravity center -extent 80x80",
      :'small'     => "-background none -gravity center -extent 40x40",
      :'tiny@2x'   => "-background none -gravity center -extent 48x48",
      :'tiny'      => "-background none -gravity center -extent 24x24",
    },
    processors: [:thumbnail, :compression]

  # validations
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true

  # url validation
  validates_format_of :url,
    :source_url, :privacy_url, :tos_url, :wikipedia_url,
    :with => URI::regexp(%w(http https ftp)),
    :message => "requires 'https://', 'http://', or 'ftp://'",
    :allow_blank => :true

  # attachment validations
  validates_attachment :logo,
    :size => { :in => 1..2048.kilobytes }
  validates_attachment_content_type :logo,
    :content_type => /^image\/(png|x-png)$/,
    :message => 'should only be png'

  # attachment deletion
  attr_accessor :delete_logo
  before_validation { logo.clear if delete_logo == '1' }

  # wikipedia
  def has_wikipedia_page
    without_wikipedia_page = [22, 25, 45]
    unless without_wikipedia_page.include?(self.id) or self.wikipedia_url == ""
      true
    end
  end

  def wikipedia_description
    sentences = 3
    url_array = self.wikipedia_url.split('/')
    url_locale = url_array[2].split('.').first
    url_remainder = url_array.drop(4)
    page_title = url_remainder.join('/')

    extract_url = "https://#{url_locale}.wikipedia.org/w/api.php?" +
      "action=query&prop=extracts&exintro=&exsentences=#{sentences}" +
      "&explaintext=&format=xml&titles=#{page_title}"

    parse = Nokogiri::XML(open(extract_url)).xpath("//extract")
    parse.first.content
  end

  def update_description
    if self.has_wikipedia_page
      self.description = self.wikipedia_description
      self.save!
    end
  end

  def self.update_descriptions
    Software.all.each { |s| s.update_description }
  end

end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :set_software, only: [:show, :edit, :update, :destroy, :history]
  before_action :set_category, only: [:show, :new, :edit, :create, :update, :history]

  # GET /softwares
  # GET /softwares.json
  def index
    @parent_path = root_path
    @page_title = t 'v.softwares.all'
    @softwares = Software.find(:all, :order => 'title')
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
    @parent_path = @category
  end

  # GET /softwares/new
  def new
    @parent_path = @category
    @page_title = t 'v.softwares.new'
    @software = Software.new
    @categories = Category.all
  end

  # GET /softwares/1/edit
  def edit
    @parent_path = category_software_path(@category, @software)
    @page_title = t 'v.softwares.edit'
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)
    @software.attributes = {'category_ids' => []}.merge(params[:software] || {})
    @software.attributes = {'protocol_ids' => []}.merge(params[:software] || {})

    respond_to do |format|
      if @software.save
        @software.update_description
        format.html { redirect_to category_software_path(@category, @software), notice: 'Software was successfully created.' }
        format.json { render action: 'show', status: :created, location: @software }
      else
        format.html { render action: 'new' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    @software.attributes = {'category_ids' => []}.merge(params[:software] || {})
    @software.attributes = {'protocol_ids' => []}.merge(params[:software] || {})
    respond_to do |format|
      if @software.update(software_params)
        @software.update_description
        format.html { redirect_to category_software_path(@category, @software), notice: 'Software was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def history
    @parent_path = category_software_path(@category, @software)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:title, :description, :url, :source_url, :privacy_url, :tos_url, :category_ids, :logo)
    end
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/_card.html.slim
- if @category != nil
  - category = @category
- else
  - category = software.categories.first

.card
  = link_to category_software_path(category, software), class: 'btn-rectangle' do 
    = image_tag software.logo.url(:'medium@2x'), class: 'card-logo'
    .title= truncate software.title, length: 23
    .category= category.title
    .rating
      span.stars
        = fa_icon 'star'
        = fa_icon 'star'
        = fa_icon 'star'
        = fa_icon 'star-half-full'
        = fa_icon 'star-o'
      span.num 
        '
        | (75)

  = link_to software.url, class: 'btn-square' do
    = fa_icon 'external-link-square'

app/views/softwares/_form.html.slim
- url = (action_name == "new" ? {:action=>"create", :controller=>"softwares"} : {:action=>"update", :controller=>"softwares"})

= form_for ([@category, @software]) do |f|
  - if @software.errors.any?
    #error_explanation
      h2 = "#{pluralize(@software.errors.count, "error")} prohibited this software from being saved:"
      ul
        - @software.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title, "#{t('Title')}*"
    = f.text_field :title

  .field
    - unless @software.has_wikipedia_page
      = f.label :description, "#{t('Description')}*"
      = f.text_area :description
    - else
      = f.label :description, "#{t('Wikipedia Description')}"
      = f.text_area :description, disabled: true

  .field
    = f.label :notes, "#{t('v.softwares.form.notes')}"
    = f.text_area :notes

  .field
    = image_tag @software.logo.url(:'medium@2x'), class: 'card-logo'
    = f.label :logo, "#{t('Logo')}"
    p.desc Square PNG up to 1024 &times; 1024px in dimensions and 512 KB in size.
    = f.file_field :logo
    - if @software.logo.exists?
      .checkbox
        = f.check_box :delete_logo
        = f.label :delete_logo, 'Destroy Logo'

  .field
    = f.label :url, "#{t('v.softwares.form.url')}*"
    = f.url_field :url
  .field
    = f.label :wikipedia_url, "#{t('v.softwares.form.wikipedia-url')}"
    = f.url_field :wikipedia_url
  .field
    = f.label :source_url, "#{t('v.softwares.form.source-url')}"
    = f.url_field :source_url
  .field
    = f.label :license_url, "#{t('v.softwares.form.license-url')}"
    = f.url_field :license_url
  .field
    = f.label :privacy_url, "#{t('v.softwares.form.privacy-url')}"
    = f.url_field :privacy_url
  .field
    = f.label :tos_url, "#{t('v.softwares.form.tos-url')}"
    = f.url_field :tos_url
    

  .field
    = f.label :protocol, t('Supported Protocols')
    ul.checkboxes
      - Protocol.all.order(:title).each do |protocol|
        li.checkbox
          = check_box_tag :protocol_ids, protocol.id, @software.protocols.include?(protocol), :name => 'software[protocol_ids][]', :id => "protocol_check_#{protocol.id}"
          = label_tag "protocol_check_#{protocol.id}", protocol.title

  .field
    = f.label :category, "#{t('v.categories.plural')}*"
    - PlatformType.all.order(:title).each do |platform_type|
      .pipe
        = platform_type.title
        |  #################################
      - platform_type.platforms.order(:title).each do |platform|
        label= link_to platform.title, platform
        ul.checkboxes
          - platform.categories.order(:title).each do |category|
            li.checkbox
              - if @category.id == category.id
                = check_box_tag :category_ids, category.id, @software.categories.include?(category), :name => 'software[category_ids][]', :id => "category_check_#{category.id}", checked: true
              - else
                = check_box_tag :category_ids, category.id, @software.categories.include?(category), :name => 'software[category_ids][]', :id => "category_check_#{category.id}"
              = label_tag "category_check_#{category.id}", category.title

  .pipe Actions
  = content_tag :button, type: 'submit', class: 'bar' do
    .label= t 'Save'
    .icon= fa_icon 'save'

app/views/softwares/_header.html.slim
.card
  .btn-rectangle
    = image_tag software.logo.url(:'medium@2x'), class: 'card-logo'
    .title= truncate software.title, length: 23
    .category= @category.title
    .rating
      span.stars
        = fa_icon 'star'
        = fa_icon 'star'
        = fa_icon 'star'
        = fa_icon 'star-half-full'
        = fa_icon 'star-o'
      span.num 
        '
        | (75)

  = link_to software.url, class: 'btn-square' do
    = fa_icon 'external-link-square'

app/views/softwares/_top.html.slim
.card
  .btn-rectangle
    = image_tag software.logo.url(:'medium@2x'), class: 'card-logo'
    .title= truncate software.title, length: 23
    .category= @category.title
    .rating
      span.stars
        = fa_icon 'star'
        = fa_icon 'star'
        = fa_icon 'star'
        = fa_icon 'star-half-full'
        = fa_icon 'star-o'
      span.num 
        '
        | (75)

  = link_to software.url, class: 'btn-square' do
    = fa_icon 'external-link-square'

app/views/softwares/edit.html.slim
== render 'form'

= link_to category_software_path(@category, @software),
  :confirm => t('Are you sure?'),
  :method => :delete,
  class: 'bar' do
  .label= t('v.softwares.destroy') 
  .icon= fa_icon 'trash-o'

app/views/softwares/history.html.slim
p#notice = notice

= render 'softwares/card', software: @software

.pipe Versions
.text-block
  ul
    - @software.versions.each do |v|
      li= v.reify

= link_to edit_category_software_path(@category, @software), class: 'bar' do
  .label= t 'Edit Software'
  .icon= fa_icon 'edit'

app/views/softwares/index.html.slim
= link_to new_software_path, class: 'bar'
  .label= t('v.softwares.new')
  .icon= fa_icon 'edit'

- @softwares.each do |software|
  = render 'softwares/card', software: software

.pipe= t 'noun.Administration'
= link_to new_software_path, class: 'bar'
  .label= t('v.softwares.new')
  .icon= fa_icon 'edit'

app/views/softwares/show.html.slim
p#notice = notice

= render 'softwares/top', software: @software

- if @software.description?
  .section
    .text-block= filter_markdown(@software.description)

- if @software.notes?
  .section
    .pipe= t 'Security Notes'
    .text-block= filter_markdown(@software.notes)

- if @software.protocols != []
  .section
    .pipe= t 'Supported Protocols'
    - @software.protocols.order(:title).each do |protocol|
      = link_to protocol, class: 'bar' do
        .label= protocol.title
        .icon= fa_icon 'angle-right'

.section
  .pipe= t 'More Info'

  = link_to @software.url, class: 'bar' do
    .label
      = t 'Official Website'
    .icon= fa_icon 'external-link'

  - if @software.wikipedia_url?
    = link_to @software.wikipedia_url, class: 'bar' do
      .label
        = t 'Wikipedia Article'
      .icon= fa_icon 'external-link'

  - if @software.privacy_url?
    = link_to @software.privacy_url, class: 'bar' do
      .label= t 'Privacy Policy'
      .icon= fa_icon 'external-link'

  - if @software.tos_url?
    = link_to @software.tos_url, class: 'bar' do
      .label= t 'Terms of Service'
      .icon= fa_icon 'external-link'

.section
  .pipe= t 'Source Code'

  - if @software.license_url?
    = link_to @software.license_url, class: 'bar'
      .label= t 'Software License'
      .icon= fa_icon 'external-link'
  - else
    .bar.warning= t 'Software License Unavailable'

  - if @software.source_url?
    = link_to @software.source_url, class: 'bar' do
      .label= t 'Source Code'
      .icon= fa_icon 'external-link'
  - else
    .bar.warning= t 'Source Code Unavailable'

.admin
  .pipe= t 'Administration'

  = link_to history_category_software_path, class: 'bar' do
    .label= t 'History'
    .icon= fa_icon 'angle-right'

  = link_to edit_category_software_path(@category, @software), class: 'bar' do
    .label= t 'v.softwares.edit'
    .icon= fa_icon 'edit'