config/routes.rb
PrismBreak::Application.routes.draw do
  resources :platform_types do
    resources :platforms
  end

  resources :platforms do
    resources :categories
  end

  resources :categories do
    resources :softwares, path: 'software' do
      get 'history', on: :member
    end
  end

  resources :protocols do
    get 'history', on: :member
  end

  get 'media', to: 'pages#media'

  filter :locale

  root 'pages#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  # associations
  belongs_to :platform

  # validations
  validates :title, presence: true

  # translations and edit history
  translates :title, :description, :versioning => true
  has_paper_trail

  # associations
  has_many :categorizations
  has_many :softwares, through: :categorizations

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @parent_path = root_path
    @page_title = t 'v.categories.all'
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @parent_path = @category.platform
    @page_title = @category.title
  end

  # GET /categories/new
  def new
    @parent_path = root_path
    @page_title = t 'v.categories.new'
    @category = Category.new
    @platforms = Platform.all
  end

  # GET /categories/1/edit
  def edit
    @parent_path = @category
    @page_title = t 'v.categories.edit'
    @platforms = Platform.all
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category.platform, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description, :platform_id)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label t 'Title'
    = f.text_field :title
  .field
    = f.label t 'Description'
    = f.text_area :description
  .field
    = f.label t 'Platform'
    ul.checkboxes
      - @platforms.order(:title).each do |platform| 
        li.checkbox
          - if platform.id == params[:platform_id].to_i
            = f.radio_button :platform_id, platform.id, id: "category_check_#{platform.id}", checked: true
          - else
            = f.radio_button :platform_id, platform.id, id: "category_check_#{platform.id}"
          = f.label "check_#{platform.id}", platform.title

  .pipe= t 'Actions'
  = content_tag :button, type: 'submit', class: 'bar' do
    .label= t 'Save'
    .icon= fa_icon 'save'

app/views/categories/all.html.slim
p#notice = notice

- @parent_category.softwares.each do |software|
  = render 'softwares/card', software: software

- @parent_category.children.order(:title).each do |subcategory|
  - if subcategory.softwares.count > 0
    .pipe= subcategory.title

    - subcategory.softwares.order(:title).each do |software|
      = render 'softwares/card', software: software

.admin
  .pipe= t 'noun.Administration'
  = link_to  edit_category_path(@parent_category), class: 'bar' do
    .label= t('v.categories.edit')
    .icon= fa_icon 'edit'
  = link_to @parent_category, :confirm => 'Are you sure?', :method => :delete, class: 'bar' do
    .label= t('v.categories.destroy')
    .icon= fa_icon 'trash-o'

app/views/categories/index.html.slim
- @categories.each do |category|
  = link_to category, class: 'bar' do
    .label
      = category.platform.title
      '
      strong= category.title
    .icon= fa_icon 'angle-right'

.pipe= t 'noun.Administration'
= link_to new_protocol_path, class: 'bar' do
  .label= t('v.categories.new')
  .icon= fa_icon 'edit'

app/views/categories/show.html.slim
p#notice = notice

- if @category.description?
  .text-block= filter_markdown(@category.description)

- @category.softwares.order(:title).each do |software|
  = render 'softwares/card', software: software

.admin
  .pipe= t 'noun.Administration'

  = link_to new_category_software_path(@category), class: 'bar'
    .label= t 'v.softwares.new'

    .icon= fa_icon 'plus'

  = link_to edit_category_path(@category), class: 'bar'
    .label= t('v.categories.edit') 
    .icon= fa_icon 'edit'

  = link_to @category, confirm: t('Are you sure?'), method: :delete, class: 'bar'
    .label= t('v.categories.destroy') 
    .icon= fa_icon 'trash-o'